CRYP-178: added update tag endpoint in api
SOEN-490-Capstone/Cryptify pull request #114
Opened 2022-11-19 22:54 UTC by Andre-Ibrahim

- added create tag endpoint
- added update tag endpoint

2022-11-19 23:09 UTC, domsec approved these changes
Looks good

2022-11-19 23:24 UTC, alexbara2000 requested changes

2022-11-19 23:24 UTC, alexbara2000 commented on packages/api/src/controllers/tags.controller.ts
> +    @Post("/users/:id/tags")
This is not part of this pr, could you please remove it?

2022-11-19 23:24 UTC, alexbara2000 commented on packages/api/src/services/tags.service.ts
> +    async create(createTagsRequest: CreateTagsRequest) {
This is not part of this pr, could you please remove it?

2022-11-19 23:24 UTC, alexbara2000 commented on packages/common/src/validations/create_tag_schema.ts
> +import * as yup from "yup";
This is not part of this pr, could you please remove it?

2022-11-19 23:24 UTC, alexbara2000 commented on packages/common/src/requests/create_tag_request.ts
> +import { InferType } from "yup";
This is not part of this pr, could you please remove it?

2022-11-20 00:15 UTC, jason-gerard reviewed
So i'll review this after the create tag endpoint is merged in?

2022-11-20 23:49 UTC, jason-gerard approved these changes

2022-11-20 23:49 UTC, jason-gerard commented on packages/api/src/controllers/tags.controller.ts
> +    @UseGuards(JwtAuthGuard, CanAccessResourceGuard)
Should be using the mutate resource guard

2022-11-20 23:49 UTC, jason-gerard commented on packages/api/src/controllers/tags.controller.ts
> +        return await this.tagsService.update(updateTagsReq);
Don't await on the return when you have a return type of promise

```suggestion
        return this.tagsService.update(updateTagsReq);
```

2022-11-20 23:49 UTC, jason-gerard commented on packages/api/src/services/tags.service.ts
> +        ) {
Can you just move these 2 calls to their own lines, the indentation looks so weird

2022-11-20 23:49 UTC, jason-gerard commented on packages/api/src/services/tags.service.ts
> +            throw new BadRequestException();
If you add a descriptive error message here, you can remove that comment above since it becomes self explanatory

```suggestion
            throw new BadRequestException("Transaction tag not found");
```

2022-11-20 23:49 UTC, jason-gerard commented on packages/api/src/controllers/tags.controller.ts
> +        const updateTagsReq = await useValidate(updateTagNameSchema, body);
```suggestion
        const updateTagReq = await useValidate(updateTagNameSchema, body);
```

2022-11-20 23:49 UTC, jason-gerard commented on packages/common/src/requests/update_tag_name_request.ts
> +export type UpdateTagNameRequest = InferType<typeof updateTagNameSchema>;
Maybe just remove the name part incase theres other stuff we can update on it in the future, no need to be specific

```suggestion
export type UpdateTagRequest = InferType<typeof updateTagSchema>;
```

2022-11-20 23:49 UTC, jason-gerard commented on packages/common/src/validations/update_tag_name_schema.ts
> +export const updateTagNameSchema = yup.object({
Same as above

```suggestion
export const updateTagSchema = yup.object({
```

2022-11-20 23:49 UTC, jason-gerard commented on packages/api/src/services/tags.service.ts
> +        // exists in the database
```suggestion
```

2022-11-21 17:37 UTC, merged