Cryp-49: implement frontend design for sign up page
SOEN-490-Capstone/Cryptify pull request #17
Opened 2022-09-21 21:20 UTC by narroarrow

Changes:
- Added front end for the sign-up page
- Modified signup verification schema to include "confirm password" field and added required statements
- Outstanding issue: error styling for the password and confirm password fields

2022-09-21 23:26 UTC, jason-gerard commented on packages/client/package.json
> +        "@fortawesome/react-native-fontawesome": "^0.3.0",
I don't think you are using these dependencies anywhere, you can probably remove them

2022-09-21 23:26 UTC, jason-gerard commented on packages/common/src/validations/sign_up_schema.ts
> +            .required("Password does not match"),
Verify these error messages with the ones in figma there are some differences between them.

2022-09-21 23:52 UTC, domsec commented on packages/common/src/validations/sign_up_schema.ts
> +            .required("Password does not match"),
Also add a period at the end of each error message

2022-09-22 00:12 UTC, domsec requested changes

2022-09-22 00:12 UTC, domsec commented on packages/client/screens/SignUpScreen.tsx
> +                                                    <MaterialIcons
This should be a font awesome icon however, there was an issue getting it to work for Sprint 1. Therefore, @jason-gerard can you please create an appropriate bug report so we don't forget to fix this in Sprint 2.

2022-09-22 00:12 UTC, domsec commented on packages/client/screens/SignUpScreen.tsx
> +                                                color="muted.400"
Should be "text.400" as described in mockup

2022-09-22 00:12 UTC, domsec commented on packages/client/screens/SignUpScreen.tsx
> +                                                color="muted.400"
Same as above comment

2022-09-22 00:12 UTC, domsec commented on packages/client/screens/SignUpScreen.tsx
> +                            </Box>
Remove as this is no longer present in the mockup

2022-09-22 00:12 UTC, domsec commented on packages/client/screens/SignUpScreen.tsx
> +    },
Please validate all css with the mobile app mockup since we are no longer designing for web.

2022-09-22 00:12 UTC, domsec commented on packages/common/src/validations/password_schema.ts
> +    .required("Enter a valid password");
Error message does not follow specs

2022-09-22 00:12 UTC, domsec commented on packages/common/src/validations/sign_up_schema.ts
> +        lastName: yup.string().matches(new RegExp("^[A-Za-z]+")).min(0).max(32).required("Enter a valid last name"),
Same as above

2022-09-22 00:12 UTC, domsec commented on packages/common/src/validations/sign_up_schema.ts
> +            .required("Password does not match"),
Same as above

2022-09-22 02:12 UTC, domsec commented on packages/client/screens/SignUpScreen.tsx
> +    },
Upon further evaluation, please ensure all styling matching mockups. Currently, an active input form (i.e. state when entering text), input border radius, and text color many more do not match the mockup.

2022-09-22 14:29 UTC, jason-gerard commented on packages/client/screens/SignUpScreen.tsx
> +                            <Text style={styles.title}>Create your account</Text>
2 of the mockups show "Create your account" the error screen shows "Create an account" can you update them to be the same, and we will mirror here?

2022-09-22 20:22 UTC, jason-gerard commented on packages/client/screens/SignUpScreen.tsx
> +                                                    <MaterialIcons
Icons are updated to the correct font awesome ones now

2022-09-22 20:23 UTC, jason-gerard commented on packages/api/src/authentication/authentication.controller.ts
> +import { JwtToken } from "@cryptify/common/src/types/jwt_token";
This was changed because the auto import kept getting messed up, we might change the name back to Token in the future

2022-09-22 20:26 UTC, jason-gerard approved these changes

2022-09-22 23:03 UTC, domsec approved these changes

2022-09-22 23:14 UTC, merged